Add ARM support
michidk/devcontainers-features pull request #5
Opened 2023-06-20 17:56 UTC by joshuanianji

This is a pretty quick fix to add arm support for versions above 0.2.0, although it doesn't check if the user has an architecture other than arm and amd. If you're fine with this, maybe we can add a short message to the NOTES.md going over supported architectures.

Maybe another way would be to check if `https://github.com/typst/typst/releases/download/v${TYPST_VERSION}/typst-$(uname -m)-unknown-linux-musl.tar.xz` is a valid url, and throwing an error if not. What do you think?

2023-06-23 17:31 UTC, michidk commented
I actually prefer this offline check. Could we keep a list of every supported architecture and check against that if the version is larger than 0.2.0? In your implementation, we assume every architecture is valid as long as not 0.2.0 or 0.1.0.
We should also keep in mind, that they could potentially release a security fix under 0.2.1 for the old version in the future  (though unlikely).

2023-06-24 18:48 UTC, joshuanianji commented
Thanks for the update! I can finish up the offline architecture check.

Do you think a possible v0.2.1 won't add new architecture support? If we can assume so, I can just check if the string begins with "0.2" or "0.1".

2023-06-25 08:35 UTC, michidk commented
> Do you think a possible v0.2.1 won't add new architecture support? If we can assume so, I can just check if the string begins with "0.2" or "0.1".

Yeah I would make that assumption

2023-06-25 08:44 UTC, michidk requested changes

2023-06-25 08:44 UTC, michidk commented on src/typst/install.sh
> +    echo "Arch test finished. Typst should be good to go!"
```suggestion
    echo "Your platform architecture is supported by Typst version v$TYPST_VERSION!"
```

2023-06-25 08:50 UTC, michidk commented
Actually, below version 0.3.0 the script would not work anyways, because the linux binary was based on glib and not musl (and therefore the filename different).
![image](https://github.com/michidk/devcontainers-features/assets/3979930/eb6c3716-ef10-47f8-814e-2c3a7b7f63f7)

But we always assume that the filename contains 'musl":
https://github.com/michidk/devcontainers-features/blob/main/src/typst/install.sh#L112

Could you also implement that it will use the glibc version for versions below 0.3.0 on the amd64 platform? This would be great.

2023-06-26 16:17 UTC, joshuanianji commented
> Could you also implement that it will use the gnu version for versions below 0.3.0 on the amd64 platform? This would be great.

Haha good catch, I can add that in. I also realized that versions 0.1 and 0.2 have `tar.gz` extensions, while 0.3 and beyond have `tar.xz`. I put both of these variations in a `LIBC_AND_EXTENSION` variable

2023-06-28 06:45 UTC, michidk commented
Thanks for the changes!
I get the following error with versions 0.1.0 and 0.2.0:
```bash
sudo VERSION=0.2.0 ./install.sh
TYPST_VERSION=0.2.0
Downloading typst version 0.2.0...
xz: (stdin): File format not recognized
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
```

2023-06-29 17:34 UTC, joshuanianji commented
Thanks! I'll add that in.

I'll add tests for just `v0.2` and `v0.5`, since I couldn't find a way to easily matrix test custom scenarios. I'll also update the `proposals` section to have the minor versions from 0.1 to 0.5 as well as `latest`.

2023-06-29 23:20 UTC, joshuanianji commented
I also found an issue with Typst versions 0.2 and 0.1 running on the devcontainer for this repo. 

The base image `mcr.microsoft.com/devcontainers/javascript-node:0-18` has a libc version of 2.31 (via `ldd --version`), so although the install script works (I think), writing `typst --version` results in the following error:

```log
typst: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by typst)
```

I'm pretty sure this is just a result of the feature starter template having an older version of the javascript-node image. When I used an updated version (either the 1-18 or 20 tag), everything worked fine. Since this might be a pretty confusing bug for others, do you want to put some sort of section in this feature's README? Maybe a "supported versions" section or something.

2023-07-01 12:22 UTC, michidk commented
Yeah that's an known issue (https://github.com/typst/typst/issues/109, fixed in https://github.com/typst/typst/pull/847) with Typst and won't be fixed for those versions.
I don't know exactly how this stuff works, but I would assume that on a system with the right glibc version, this typst executable would still work.

Great what you implemented there! Love the tests as well.

The `'javascript-node-0-18'` fails on the CI. As soon as this is fixed, I think this is ready to merge.

2023-07-03 18:04 UTC, joshuanianji commented
Thanks! I'll delete the `javascript-node-0-18` test and add a note

2023-07-04 05:47 UTC, michidk approved these changes

2023-07-04 05:48 UTC, michidk commented
Really cool! Thanks a lot for your changes!

2023-07-04 05:49 UTC, merged